sonar.projectKey=clahan-academy
sonar.organization=clahan-academy
sonar.projectName=Clahan Academy V2
sonar.sources=services
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/venv/**